version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=keycloak_user
      - POSTGRES_DB=keycloak_db
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres:5432   # The hostname is the name of the postgres service
      - DB_DATABASE=keycloak_db  # The database name
      - DB_USER=keycloak_user    # The user configured for Keycloak to access Postgres
      - DB_PASSWORD=secret      # The password for the postgres user
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - keycloak-network
    command:
      - start-dev

networks:
  keycloak-network:
    driver: bridge
